name: Python application

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Clone repo
      uses: actions/checkout@v4
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build proj
      run: |
        pip install build
        python -m build
        ls -l dist || true
        
    - name: Uni test
      run: |
        pytest -q
